// Catálogos UNAMAD-internos, derivados del análisis de los archivos históricos
// (CAS 2024-2026 e Indeterminados). NO van al export SUNEDU — se usan solo
// como sugerencias en los formularios (datalist) para evitar typos y datos
// inconsistentes como "SECUNDARA" o "INGENIREIA".
//
// Los valores están normalizados en MAYÚSCULAS y sin tildes excepto donde
// el uso es estándar. Si una sede agrega nuevas plazas o cargos, simplemente
// se agregan a estas listas y la UI las sugiere a la siguiente carga.

export const GRADOS_MAXIMOS: readonly string[] = [
  "PRIMARIA",
  "SECUNDARIA COMPLETA",
  "TECNICO",
  "ESTUDIANTE",
  "EGRESADO",
  "BACHILLER",
  "TITULADO",
  "LICENCIADO",
  "ABOGADO",
  "CONTADOR PUBLICO",
  "INGENIERO",
  "MEDICO",
  "MAGISTER",
  "DOCTOR",
];

export const GRUPOS_CARRERA: readonly string[] = [
  "ADMINISTRACION",
  "CONTABILIDAD",
  "INGENIERIA",
  "DERECHO",
  "EDUCACION",
  "SALUD",
  "MEDICINA",
  "ENFERMERIA",
  "SECRETARIADO",
  "COMUNICACION",
  "ANTROPOLOGIA",
  "TRABAJO SOCIAL",
  "ECOTURISMO",
];

export const CARRERAS_COMUNES: readonly string[] = [
  "ADMINISTRACION Y NEGOCIOS INTERNACIONALES",
  "CONTABILIDAD Y FINANZAS",
  "DERECHO Y CIENCIAS POLITICAS",
  "INGENIERIA DE SISTEMAS E INFORMATICA",
  "INGENIERIA AGROINDUSTRIAL",
  "INGENIERIA FORESTAL Y MEDIO AMBIENTE",
  "MEDICINA VETERINARIA Y ZOOTECNIA",
  "EDUCACION INICIAL",
  "EDUCACION PRIMARIA",
  "EDUCACION SECUNDARIA",
  "EDUCACION MATEMATICA Y COMPUTACION",
  "EDUCACION LENGUA Y LITERATURA",
  "ENFERMERIA",
  "ECOTURISMO",
  "ANTROPOLOGIA",
  "TRABAJO SOCIAL",
  "SECRETARIADO EJECUTIVO",
  "ADMINISTRACION Y MARKETING",
  "ADMINISTRACION DE EMPRESAS",
  "CIENCIAS DE LA COMUNICACION",
];

// Cargos canónicos consolidados de CAS + Indeterminados.
export const CARGOS_DETALLADOS: readonly string[] = [
  "AGENTE DE SEGURIDAD",
  "ASISTENTE ADMINISTRATIVO",
  "ASISTENTE DE ESTADISTICA E INFORMATICA",
  "ASISTENTE LEGAL",
  "AUXILIAR ADMINISTRATIVO",
  "CAMAROGRAFO",
  "CARPINTERO",
  "CHOFER",
  "CONSERJE",
  "COORDINADOR(A)",
  "DIRECTOR",
  "DIRECTOR (ADMINISTRADOR)",
  "ENFERMERO(A)",
  "ESPECIALISTA ACADEMICO",
  "ESPECIALISTA ADMINISTRATIVO",
  "ESPECIALISTA EN ADQUISICIONES",
  "ESPECIALISTA EN BASE DE DATOS",
  "ESPECIALISTA EN REDES",
  "ESPECIALISTA EN SOPORTE INFORMATICO",
  "ESPECIALISTA INFORMATICO",
  "ESPECIALISTA LEGAL",
  "GUARDIAN",
  "JARDINERO",
  "JEFE",
  "MEDICO",
  "OPERADOR ADMINISTRATIVO",
  "PERSONAL DE LIMPIEZA",
  "SECRETARIA",
  "SECRETARIO GENERAL",
  "SOPORTE TECNICO",
  "TECNICO ADMINISTRATIVO I",
  "TECNICO ADMINISTRATIVO II",
];

// Plazas/oficinas comunes del organigrama UNAMAD. Lista derivada de
// histórico — sugerencias para autocomplete, el usuario puede tipear otras.
export const PLAZAS_COMUNES: readonly string[] = [
  // Direcciones generales
  "DIRECCION GENERAL DE ADMINISTRACION",
  "DIRECCION GENERAL DE INVESTIGACION",
  "DIRECCION DE ADMISION",
  "DIRECCION DE ASUNTOS ACADEMICOS",
  "DIRECCION DE BIBLIOTECA CENTRAL",
  "DIRECCION DE BIENESTAR UNIVERSITARIO",
  "DIRECCION DE INCUBADORAS DE EMPRESAS",
  // Vicerrectorados
  "RECTORADO",
  "VICERRECTORADO ACADEMICO",
  "VICERRECTORADO DE INVESTIGACION",
  "VICERRECTORADO DE INVESTIGACION - HERBARIO",
  "VICERRECTORADO DE INVESTIGACION - REPOSITORIO",
  // Oficinas
  "OFICINA DE ASESORIA JURIDICA",
  "OFICINA DE COMUNICACION E IMAGEN INSTITUCIONAL",
  "OFICINA DE GESTION DE LA CALIDAD",
  "OFICINA DE PLANEAMIENTO Y PRESUPUESTO",
  "OFICINA DE TECNOLOGIAS DE LA INFORMACION",
  // Unidades
  "UNIDAD DE ABASTECIMIENTO",
  "UNIDAD DE ABASTECIMIENTO - UNIDAD DE ALMACEN",
  "UNIDAD DE BIENES PATRIMONIALES",
  "UNIDAD DE EVALUACION Y DESARROLLO AL DOCENTE",
  "UNIDAD DE GRADOS Y TITULOS",
  "UNIDAD DE PRESUPUESTO",
  "UNIDAD DE PLANEAMIENTO ESTRATEGICO",
  "UNIDAD DE RECURSOS HUMANOS",
  "UNIDAD DE RECURSOS HUMANOS - SALUD OCUPACIONAL",
  "UNIDAD DE RECURSOS HUMANOS - REMUNERACIONES",
  "UNIDAD DE RECURSOS HUMANOS - SECRETARIA TECNICA PAD",
  "UNIDAD DE REGISTROS ACADEMICOS Y ARCHIVO",
  "UNIDAD DE SEGUIMIENTO AL EGRESADO Y BOLSA DE TRABAJO",
  "UNIDAD DE SERVICIOS GENERALES",
  "UNIDAD DE TESORERIA",
  "UNIDAD DE TRAMITE DOCUMENTARIO",
  "UNIDAD FORMULADORA",
  // Secretaría
  "SECRETARIA GENERAL",
  // Facultades / escuelas / departamentos académicos
  "FACULTAD DE CIENCIAS EMPRESARIALES",
  "FACULTAD DE EDUCACION",
  "FACULTAD DE INGENIERIA",
  "ESCUELA PROFESIONAL DE ADMINISTRACION Y NEGOCIOS INTERNACIONALES",
  "ESCUELA PROFESIONAL DE CONTABILIDAD Y FINANZAS",
  "ESCUELA PROFESIONAL DE DERECHO Y CIENCIAS POLITICAS",
  "ESCUELA PROFESIONAL DE ECOTURISMO",
  "ESCUELA PROFESIONAL DE EDUCACION Y HUMANIDADES",
  "ESCUELA PROFESIONAL DE ENFERMERIA",
  "ESCUELA PROFESIONAL DE INGENIERIA AGROINDUSTRIAL",
  "ESCUELA PROFESIONAL DE INGENIERIA DE SISTEMAS E INFORMATICA",
  "ESCUELA PROFESIONAL DE INGENIERIA FORESTAL Y MEDIO AMBIENTE",
  "ESCUELA PROFESIONAL DE MEDICINA VETERINARIA Y ZOOTECNIA",
  "DEPARTAMENTO ACADEMICO DE CIENCIAS BASICAS",
  "DEPARTAMENTO ACADEMICO DE DERECHO Y CIENCIAS POLITICAS",
  "DEPARTAMENTO ACADEMICO DE ECOTURISMO",
  "DEPARTAMENTO ACADEMICO DE ENFERMERIA",
  "DEPARTAMENTO ACADEMICO DE INGENIERIA FORESTAL Y MEDIO AMBIENTE",
  "DEPARTAMENTO ACADEMICO DE MEDICINA VETERINARIA Y ZOOTECNIA",
  // Otros
  "BIBLIOTECA CENTRAL",
  "TRIBUNAL DE HONOR",
  "VIVERO FORESTAL - FUNDO EL BOSQUE",
];
